### ISSUE TITLE
is this work with RN25/RN26 and react 15?

### ISSUE THREAD

**Issue by sibelius** [lelandrichardson/react-native-mock#42]

**Comment by sibelius** [comment]
current error with React 15

``` jsx
module.js:440
    throw err;
    ^

Error: Cannot find module 'react/lib/cloneWithProps'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (enzyme-example-react-native/node_modules/react-addons-clone-with-props/index.js:1:80)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (enzyme-example-react-native/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (enzyme-example-react-native/node_modules/react-native-mock/build/react-native.js:118:19)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (enzyme-example-react-native/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (enzyme-example-react-native/node_modules/react-native-mock/mock.js:1:85)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (enzyme-example-react-native/node_modules/babel-register/lib/node.js:166:7)
npm ERR! Test failed.  See above for more details.

```

**Comment by Purii** [comment]
> Note: cloneWithProps is deprecated. Use React.cloneElement instead.
> (https://facebook.github.io/react/docs/clone-with-props.html)
