### ISSUE TITLE
InteractionManager.createInteractionHandle is not a function

### ISSUE THREAD

**Issue by tomkur** [lelandrichardson/react-native-mock#49]
The minimal mocha test suite to reproduce this problem is following:

``` js
// tests/animatedTest.js
import {Animated} from 'react-native'

describe('Animated', () => {
  it('should animate', () => {
    const value = new Animated.Value(0)
    Animated.timing(
      value,
      {
        toValue: 1,
        delay: 1000
      }
    ).start()
  })
})
```

When running with:

```
mocha --require react-native-mock/mock --compilers js:babel-core/register tests/animatedTest.js       
```

I get the following error:

```
     TypeError: _InteractionManager2.default.createInteractionHandle is not a function
      at AnimatedValue.animate (node_modules/react-native-mock/build/api/Animated/AnimatedImplementation.js:750:52)
      at Object.start (node_modules/react-native-mock/build/api/Animated/AnimatedImplementation.js:1543:23)
      at Context.<anonymous> (animatedTest.js:12:7)
```

It looks like [InteractionManager.js](https://github.com/lelandrichardson/react-native-mock/blob/6e1c585916aeca7063a4e024a348c433aa0fcad8/src/api/InteractionManager.js) is missing `module.exports` statement.

**Comment by RealOrangeOne** [comment]
Ah yes that does appear to be a problem. Fancy submitting a PR for it?

**Comment by tomkur** [comment]
I'm on it.
