### ISSUE TITLE
 Cannot find module 'keyMirror'

### ISSUE THREAD

**Issue by pranjalnanavaty** [lelandrichardson/react-native-mock#7]
After cloning the repository and running npm install. I tried to run npm test and this error showed up.

> react-native-mock@0.0.5 test /home/pranjal/react-native-mock
> mocha --require babel-core/register test/*_/_.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'keyMirror'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pranjal/react-native-mock/src/api/InteractionManager.js:3:18)
    at Module._compile (module.js:410:26)
    at loader (/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pranjal/react-native-mock/src/api/Animated/AnimatedImplementation.js:21:27)
    at Module._compile (module.js:410:26)
    at loader (/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pranjal/react-native-mock/src/api/Animated/index.js:21:31)
    at Module._compile (module.js:410:26)
    at loader (/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (react-native.js:55:13)
    at Module._compile (module.js:410:26)
    at loader (/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pranjal/react-native-mock/test/basic-test.js:3:20)
    at Module._compile (module.js:410:26)
    at loader (/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/pranjal/react-native-mock/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/pranjal/react-native-mock/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/pranjal/react-native-mock/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/pranjal/react-native-mock/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/home/pranjal/react-native-mock/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! Test failed.  See above for more details.

**Comment by lelandrichardson** [comment]
@Pranjal5 not sure why this didn't get caught. I will be setting up CI soon so this will not happen moving forward.

**Comment by lelandrichardson** [comment]
(FWIW, the npm published module should work fine)

**Comment by mroswald** [comment]
could you please push a new release? 0.0.5 does not include the fix

**Comment by lelandrichardson** [comment]
my apologies. I thought I had already done this!  It's out now on 0.0.6...

**Comment by mroswald** [comment]
thanks!
